name: gh3Fs.action.js
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Target directory path to save result'
        required: false
        default: ''
      pinned:
        description: 'Comma separated list of pinned repositories'
        required: false
        default: ''
      clean:
        description: 'Clear Workflow Runs to a minimal set'
        required: false
        default: ''
      label:
        description: 'Custom account labeling'
        required: false
        default: ''
      debug:
        description: 'Make it verbose'
        required: false
        default: ''
  schedule:
    - cron: '0 * * * *'

jobs:
  best_job_ever:
    runs-on: ubuntu-latest
    name: Generate statistics
    steps:
      - uses: actions/checkout@v2
      -   name: SSH
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
              ssh-agent -a $SSH_AUTH_SOCK > /dev/null
              ssh-add - <<< "${{ secrets.SSH_PK }}"

      - name: Checkout private repo
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock 
        uses: actions/checkout@v2
        with:
          repository: 3F/gh3Fs.action.js
          ref: refs/heads/master
          token: ${{ secrets.GH_S_PK }}
          persist-credentials: false
          path: ./
          
      - name: Update using node cli
        run: node ./dist/index.js token:${{ secrets.GH_S_PK }} path:${{ github.event.inputs.path || 'generated/' }} pinned:${{ github.event.inputs.pinned || 'Conari,LX4Cnh,regXwild,MvsSln,Jt,IeXod,vsSolutionBuildEvent,sandbox,UnmanagedEmitCalli,aml_s905_uboot,GetNuTool,Fnv1a128,LuNari,hMSBuild,Huid,vsCommandEvent,coreclr,DllExport,E-MSBuild,TmVTweaks,MoConTool,Examples,netfx4sdk' }} clean:${{ github.event.inputs.clean || '300' }} label:${{ github.event.inputs.label || 'github/3F' }} debug:${{ github.event.inputs.debug || 'true' }}
        
        
      ## FIXME: 
      ## SyntaxError: Unexpected token '('
      ##   at Module._compile (internal/modules/cjs/loader.js:895:18)
#      
#       - uses: ./
#         name: Update using github core
#         id: gh3Fs
#         with:
#           path: ${{ github.event.inputs.path }}
#           pinned: ${{ github.event.inputs.pinned }}
#       - name: Get the output
#         run: echo "Done. ${{ steps.gh3Fs.outputs.result }}"
